services:
  db:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_DB=teste
      - POSTGRES_PASSWORD=123456
    container_name: database
    restart: always
  minio:
    image:  minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"